spring:
  application:
    name: HomeRepOrderService
  datasource:
    url: jdbc:postgresql://localhost:5433/homerep_orderservice
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8084
