spring:
  application:
    name: HomeRepOrderService
  datasource:
    url: jdbc:postgresql://localhost:5434/homerep_orderservice
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers:
#      - localhost:9092
      - localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8084
grpc:
  client:
    location-service:
      address: static://localhost:50051
      negotiation-type: plaintext
  server:
    port: 9091
